export enum BOARD {
  FLIP_TILE = "FLIP_TILE",
  RECORD_MOVE = "RECORD_MOVE",
  RECORD_MATCH = "RECORD_MATCH",
  FILL_BOARD = "FILL_BOARD",
}

export enum TOGGLE {
  THEME = "TOGGLE_THEME",
  PLAYERS = "TOGGLE_PLAYERS",
  GRID_SIZE = "TOGGLE_GRID_SIZE",
}
